<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class NotchAddonsSettings {
	private $notch_addons_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'notch_addons_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'notch_addons_page_init' ) );
	}

	public function notch_addons_add_plugin_page() {
		add_menu_page(
			'Notch Addons', // page_title
			'Notch Addons', // menu_title
			'manage_options', // capability
			'notch-addons', // menu_slug
			array( $this, 'notch_addons_create_admin_page' ), // function
			'dashicons-smiley', // icon_url
			10 // position
		);
	}

	public function notch_addons_create_admin_page() {
		$this->notch_addons_options = get_option( 'notch_addons_option_name' ); ?>

		<div class="wrap">
			<h2>Notch Addons</h2>
			<p>Notch Addons Settings</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'notch_addons_option_group' );
					do_settings_sections( 'notch-addons-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function notch_addons_page_init() {
		register_setting(
			'notch_addons_option_group', // option_group
			'notch_addons_option_name', // option_name
			array( $this, 'notch_addons_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'notch_addons_setting_section', // id
			'Settings', // title
			array( $this, 'notch_addons_section_info' ), // callback
			'notch-addons-admin' // page
		);

		add_settings_field(
			'notch_addons_blog_post', // id
			'Blog Post', // title
			array( $this, 'notch_addons_blog_post_validation' ), // callback
			'notch-addons-admin', // page
			'notch_addons_setting_section' // section
		);

		add_settings_field(
			'notch_addons_image_gallery', // id
			'Image Gallery', // title
			array( $this, 'notch_addons_image_gallery_validation' ), // callback
			'notch-addons-admin', // page
			'notch_addons_setting_section' // section
		);

		add_settings_field(
			'notch_addons_image_compare', // id
			'Image Compare', // title
			array( $this, 'notch_addons_image_compare_validation' ), // validation
			'notch-addons-admin', // page
			'notch_addons_setting_section' // section
		);

		add_settings_field(
			'notch_addons_timeline', // id
			'Timeline', // title
			array( $this, 'notch_addons_timeline_validation' ), // validation
			'notch-addons-admin', // page
			'notch_addons_setting_section' // section
		);
	}

	public function notch_addons_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['notch_addons_blog_post'] ) ) {
			$sanitary_values['notch_addons_blog_post'] = $input['notch_addons_blog_post'];
		}

		if ( isset( $input['notch_addons_image_gallery'] ) ) {
			$sanitary_values['notch_addons_image_gallery'] = $input['notch_addons_image_gallery'];
		}

		if ( isset( $input['notch_addons_image_compare'] ) ) {
			$sanitary_values['notch_addons_image_compare'] = $input['notch_addons_image_compare'];
		}

		if ( isset( $input['notch_addons_timeline'] ) ) {
			$sanitary_values['notch_addons_timeline'] = $input['notch_addons_timeline'];
		}

		return $sanitary_values;
	}

	public function notch_addons_section_info() {
		
	}

	public function notch_addons_blog_post_validation() {
		printf(
			'<input type="checkbox" name="notch_addons_option_name[notch_addons_blog_post]" id="notch_addons_blog_post" value="notch_addons_blog_post" %s>',
			( isset( $this->notch_addons_options['notch_addons_blog_post'] ) && $this->notch_addons_options['notch_addons_blog_post'] === 'notch_addons_blog_post' ) ? 'checked' : ''
		);
	}

	public function notch_addons_image_gallery_validation() {
		printf(
			'<input type="checkbox" name="notch_addons_option_name[notch_addons_image_gallery]" id="notch_addons_image_gallery" value="notch_addons_image_gallery" %s>',
			( isset( $this->notch_addons_options['notch_addons_image_gallery'] ) && $this->notch_addons_options['notch_addons_image_gallery'] === 'notch_addons_image_gallery' ) ? 'checked' : ''
		);
	}

	public function notch_addons_image_compare_validation() {
		printf(
			'<input type="checkbox" name="notch_addons_option_name[notch_addons_image_compare]" id="notch_addons_image_compare" value="notch_addons_image_compare" %s>',
			( isset( $this->notch_addons_options['notch_addons_image_compare'] ) && $this->notch_addons_options['notch_addons_image_compare'] === 'notch_addons_image_compare' ) ? 'checked' : ''
		);
	}

	public function notch_addons_timeline_validation() {
		printf(
			'<input type="checkbox" name="notch_addons_option_name[notch_addons_timeline]" id="notch_addons_timeline" value="notch_addons_timeline" %s>',
			( isset( $this->notch_addons_options['notch_addons_timeline'] ) && $this->notch_addons_options['notch_addons_timeline'] === 'notch_addons_timeline' ) ? 'checked' : ''
		);
	}

}
if ( is_admin() )
	$notch_addons = new NotchAddonsSettings();
/* 
 * Retrieve this value with:
 * $notch_addons_options = get_option( 'notch_addons_option_name' ); // Array of All Options
 * $blog_post_0 = $notch_addons_options['blog_post_0']; // Blog Post
 * $notch_addons_image_gallery = $notch_addons_options['notch_addons_image_gallery']; // Image Gallery
 * $notch_addons_image_compare = $notch_addons_options['notch_addons_image_compare']; // Image Compare
 * $notch_addons_timeline = $notch_addons_options['notch_addons_timeline']; // Timeline
 */
